-- CreateEnum
CREATE TYPE "Category" AS ENUM ('HEAT_STORAGE_COOLING_EQUIPMENT_AND_MATERIALS', 'INTEGRATED_ENERGY_SYSTEM_FOR_GENERATION', 'HYDROGEN_AMMONIA_HYDROGEN_FUSION_TECHNOLOGY', 'TEACHING_SCIENTIFIC_LABORATORY_EQUIPMENT');

-- CreateTable
CREATE TABLE "Product" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "image" TEXT NOT NULL,
    "category" "Category" NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);
